


crawler:
    userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36
    seek:
        url: https://jobsearch-api.cloud.seek.com.au/search
        callback: jQuery18203420653892844612_1477784271109
        nation: 3001
        itemsPerPage: 20
        from_site: SEEK
        detail_url: https://www.seek.co.nz/job/
