version: '2'
services:
    cv-app:
        image: cv
        external_links:
            - cv-mysql:mysql
            - cv-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cv?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=30 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    cv-mysql:
        extends:
            file: mysql.yml
            service: cv-mysql
    cv-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: cv-elasticsearch
