version: '2'
services:
    cv-app:
        image: flying3615/cv:latest
        external_links:
            - cv-mysql:mysql
#            - cv-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cv?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
#            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8181:8181
    cv-mysql:
        extends:
            file: mysql.yml
            service: cv-mysql
#    cv-elasticsearch:
#        extends:
#            file: elasticsearch.yml
#            service: cv-elasticsearch
